In [33]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
#importing the dataset
data=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\testprojects\dataset\covid dataset csv\Covid Data.csv")

In [35]:
print(data)

         USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  \
0            2             1    1             1  03/05/2020       97   
1            2             1    2             1  03/06/2020       97   
2            2             1    2             2  09/06/2020        1   
3            2             1    1             1  12/06/2020       97   
4            2             1    2             1  21/06/2020       97   
...        ...           ...  ...           ...         ...      ...   
1048570      2            13    2             1  9999-99-99       97   
1048571      1            13    2             2  9999-99-99        2   
1048572      2            13    2             1  9999-99-99       97   
1048573      2            13    2             1  9999-99-99       97   
1048574      2            13    2             1  9999-99-99       97   

         PNEUMONIA  AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  \
0                1   65         2         2  ...       2        2 

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype 
---  ------                --------------    ----- 
 0   USMER                 1048575 non-null  int64 
 1   MEDICAL_UNIT          1048575 non-null  int64 
 2   SEX                   1048575 non-null  int64 
 3   PATIENT_TYPE          1048575 non-null  int64 
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64 
 6   PNEUMONIA             1048575 non-null  int64 
 7   AGE                   1048575 non-null  int64 
 8   PREGNANT              1048575 non-null  int64 
 9   DIABETES              1048575 non-null  int64 
 10  COPD                  1048575 non-null  int64 
 11  ASTHMA                1048575 non-null  int64 
 12  INMSUPR               1048575 non-null  int64 
 13  HIPERTENSION          1048575 non-null  int64 
 14  OTHER_DISEASE         1048575 non-null  int64 
 15

In [37]:
data = data.drop('DATE_DIED', axis=1)

In [38]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(X)

[[ 2  1  1 ...  2  2  3]
 [ 2  1  2 ...  1  2  5]
 [ 2  1  2 ...  2  2  3]
 ...
 [ 2 13  2 ...  2  2  7]
 [ 2 13  2 ...  2  2  7]
 [ 2 13  2 ...  2  2  7]]


In [39]:
print(y)

[97 97  2 ... 97 97 97]


In [40]:
#Handling Missing Values
from sklearn.impute  import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,0:18])
X[:,0:18]=imputer.transform(X[:,0:18])


In [41]:
print(X)

[[ 2  1  1 ...  2  2  3]
 [ 2  1  2 ...  1  2  5]
 [ 2  1  2 ...  2  2  3]
 ...
 [ 2 13  2 ...  2  2  7]
 [ 2 13  2 ...  2  2  7]
 [ 2 13  2 ...  2  2  7]]


In [42]:
#Spliting Data into Test and Train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [43]:
print(X_train)

[[ 2  4  1 ...  2  2  3]
 [ 2 12  1 ...  2  2  7]
 [ 1  6  1 ...  2  2  3]
 ...
 [ 2  4  2 ...  2  1  3]
 [ 2 12  2 ...  2  2  5]
 [ 2  4  1 ...  2  2  3]]


In [44]:
print(X_test)

[[ 2 12  1 ...  2  2  7]
 [ 2 12  2 ...  2  2  7]
 [ 2 12  1 ...  2  2  7]
 ...
 [ 2  4  1 ...  2  2  7]
 [ 2  4  1 ...  2  2  7]
 [ 1 12  2 ...  2  1  7]]


In [45]:
print(y_train)

[ 2 97 97 ... 97 97 97]


In [46]:
print(y_test)

[97 97 97 ... 97 97 97]


In [47]:
#Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[2 2 1 ... 2 2 2]


In [48]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, :9] = sc.fit_transform(X_train[:, :9])
X_test[:, :9] = sc.transform(X_test[:, :9])

print(X_train)


[[ 0 -1  0 ...  2  2  3]
 [ 0  0  0 ...  2  2  7]
 [-1  0  0 ...  2  2  3]
 ...
 [ 0 -1  1 ...  2  1  3]
 [ 0  0  1 ...  2  2  5]
 [ 0 -1  0 ...  2  2  3]]


In [49]:
print(X_test)

[[ 0  0  0 ...  2  2  7]
 [ 0  0  1 ...  2  2  7]
 [ 0  0  0 ...  2  2  7]
 ...
 [ 0 -1  0 ...  2  2  7]
 [ 0 -1  0 ...  2  2  7]
 [-1  0  1 ...  2  1  7]]
