**Data Preprocessing**


1.   Importing Libraries
2.   Importing Data
3.   Handling Missing Data or Value
4.   Encoding Categorical data
5.   Feature SCaling



In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [61]:
dataset=pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
print(dataset)



         id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  former

In [62]:
dataset.drop(columns=['id'], inplace=True)

In [63]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   object 
 5   work_type          5110 non-null   object 
 6   Residence_type     5110 non-null   object 
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     5110 non-null   object 
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB


In [53]:
"""X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values"""

In [54]:
"""print(X)"""


[['Male' 67.0 0 ... 228.69 36.6 'formerly smoked']
 ['Female' 61.0 0 ... 202.21 nan 'never smoked']
 ['Male' 80.0 0 ... 105.92 32.5 'never smoked']
 ...
 ['Female' 35.0 0 ... 82.99 30.6 'never smoked']
 ['Male' 51.0 0 ... 166.29 25.6 'formerly smoked']
 ['Female' 44.0 0 ... 85.28 26.2 'Unknown']]


In [55]:
"" "print(y) """

[1 1 1 ... 0 0 0]


**Encoding Categorical Data**

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Define transformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [6])], remainder='passthrough')

# Fit and transform
X=np.array(ct.fit_transform(X))




In [65]:
dataset= pd.get_dummies(data =dataset, columns =['gender','ever_married','work_type','Residence_type','smoking_status'],drop_first=True )


In [66]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [67]:
print(X)

[[67.0 0 1 ... True True False]
 [61.0 0 0 ... False False True]
 [80.0 0 1 ... False False True]
 ...
 [35.0 0 0 ... False False True]
 [51.0 0 0 ... False True False]
 [44.0 0 0 ... True False False]]


In [69]:
print(y)

[False False False ... False False False]


In [70]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 0 ... 0 0 0]


**Handling Missing Values**

In [72]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,0:9])
X[:,0:9]=imputer.transform(X[:,0:9])

**Splitting the dataset**


In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [74]:
print(X_train)

[[79.0 0.0 0.0 ... False True False]
 [62.0 0.0 0.0 ... True False False]
 [21.0 0.0 0.0 ... False False True]
 ...
 [1.16 0.0 0.0 ... True False False]
 [80.0 0.0 0.0 ... False True False]
 [46.0 0.0 0.0 ... False False False]]


In [75]:
print(X_test)

[[31.0 0.0 0.0 ... False False False]
 [40.0 0.0 0.0 ... False False True]
 [8.0 0.0 0.0 ... True False False]
 ...
 [49.0 1.0 0.0 ... False True False]
 [56.0 0.0 0.0 ... True False False]
 [78.0 1.0 1.0 ... False False True]]


In [76]:
print(y_test)

[0 0 0 ... 0 1 0]


In [77]:
print(y_train)

[0 0 0 ... 0 0 1]


Feature Sampling


In [83]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, :9] = sc.fit_transform(X_train[:, :9])
X_test[:, :9] = sc.transform(X_test[:, :9])

print(X_train)


[[1.5841547240261877 -0.3219809097811624 -0.23618874648667124 ... False
  True False]
 [0.8297076566842779 -0.3219809097811624 -0.23618874648667124 ... True
  False False]
 [-0.9898411527873868 -0.3219809097811624 -0.23618874648667124 ... False
  False True]
 ...
 [-1.870325259614651 -0.3219809097811624 -0.23618874648667124 ... True
  False False]
 [1.6285339632815943 -0.3219809097811624 -0.23618874648667124 ... False
  True False]
 [0.11963982859777464 -0.3219809097811624 -0.23618874648667124 ... False
  False False]]


In [84]:
print(X_test)


[[-0.5460487602333223 -0.3219809097811624 -0.23618874648667124 ... False
  False False]
 [-0.1466356069346641 -0.3219809097811624 -0.23618874648667124 ... False
  False True]
 [-1.5667712631076705 -0.3219809097811624 -0.23618874648667124 ... True
  False False]
 ...
 [0.252777546363994 3.1057741922641204 -0.23618874648667124 ... False
  True False]
 [0.5634322211518392 -0.3219809097811624 -0.23618874648667124 ... True
  False False]
 [1.5397754847707812 3.1057741922641204 4.2339019740573525 ... False
  False True]]
